IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SR-ALAMO\SQLServer')
CREATE LOGIN [SR-ALAMO\SQLServer] FROM WINDOWS
GO
CREATE USER [SR-ALAMO\SQLServer] FOR LOGIN [SR-ALAMO\SQLServer]
GO
